version: '3'

services:
  iroha-node0:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node0
    ports:
      - "50000:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg0
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache
      - KEY=nodes/node0
    depends_on:
      - iroha_pg0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg0:5432",
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node0/config.sample", 
      "--keypair_name", "node0", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node1:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node1
    ports:
      - "50001:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node1
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg1
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg1:5432",
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block",
      "--config", "/opt/iroha/nodes/node1/config.sample", 
      "--keypair_name", "node1", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE


  iroha-node2:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node2
    ports:
      - "50002:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg2
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node2
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg2
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg2:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node2/config.sample", 
      "--keypair_name", "node2", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE


  iroha-node3:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node3
    ports:
      - "50003:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg3
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node3
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg3
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg3:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node3/config.sample", 
      "--keypair_name", "node3", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node4:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node4
    ports:
      - "50004:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg4
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node4
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg4
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", "iroha_pg4:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node4/config.sample", 
      "--keypair_name", "node4", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node5:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node5
    ports:
      - "50005:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg5
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache
      - KEY=nodes/node5
    depends_on:
      - iroha_pg5
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg5:5432",
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node5/config.sample", 
      "--keypair_name", "node5", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node6:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node6
    ports:
      - "50006:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg6
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node6
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg6
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg6:5432",
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block",
      "--config", "/opt/iroha/nodes/node6/config.sample", 
      "--keypair_name", "node6", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE


  iroha-node7:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node7
    ports:
      - "50007:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg7
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node7
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg7
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg7:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node7/config.sample", 
      "--keypair_name", "node7", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE


  iroha-node8:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node8
    ports:
      - "50008:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg8
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node8
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg8
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg8:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node8/config.sample", 
      "--keypair_name", "node8", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE

  iroha-node9:
    image: hyperledger/iroha:1.0.0_rc5
    container_name: iroha_node9
    ports:
      - "50009:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_pg9
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - KEY=nodes/node9
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - iroha_pg9
      - iroha-node0
    entrypoint: ["./wait-for-it.sh", 
      "iroha_pg9:5432", 
      "--", "irohad", "--genesis_block", "/opt/iroha/genesis.block", 
      "--config", "/opt/iroha/nodes/node9/config.sample", 
      "--keypair_name", "node9", "--overwrite-ledger"]
    tty: true
    volumes:
      - ./../nodes/:/opt/iroha/nodes
      - ./:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE





  iroha_pg0:
    image: postgres:9.5
    container_name: iroha_pg0
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg1:
    image: postgres:9.5
    container_name: iroha_pg1
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg2:
    image: postgres:9.5
    container_name: iroha_pg2
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg3:
    image: postgres:9.5
    container_name: iroha_pg3
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg4:
    image: postgres:9.5
    container_name: iroha_pg4
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg5:
    image: postgres:9.5
    container_name: iroha_pg5
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg6:
    image: postgres:9.5
    container_name: iroha_pg6
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg7:
    image: postgres:9.5
    container_name: iroha_pg7
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg8:
    image: postgres:9.5
    container_name: iroha_pg8
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

  iroha_pg9:
    image: postgres:9.5
    container_name: iroha_pg9
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=helloworld

volumes:
  ccache-data:
