node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org5peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org10peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org20peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org30peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org40peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org50peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org60peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org70peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org80peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org90peer/fabric-go.json 
node run-benchmark.js -c ../benchmark/simple/fabricTest.yaml -n ../network/fabric-v1.4/1org100peer/fabric-go.json 